version: '3.7'
services:
  mongodb_container:
    container_name: mongo
    image: mongo
    # environment:
    #   MONGO_INITDB_DATABASE: rootdatabase
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: password
    #   MONGO_USERNAME: admin
    #   MONGO_PASSWORD: password
    ports:
      - 27017:27017
    # volumes:
    #   - mongodb_data_container:/data/db
#   mongo-express:
    # image: mongo-express
    # ports:
        # - "8081:8081"
# volumes:
#   mongodb_data_container: